### ISSUE TITLE
AccessTokenを更新する方法

### ISSUE THREAD

**Issue by hardreggaecafe** [infinity-octaver/ne_api#9]
バッチ処理を書いているのですが、最初のAccessTokenは画面からやらないといけないのはわかりますが、その後にne_api使って継続的にTokenをリフレッシュする方法を教えて下さい。

**Comment by yuuna** [comment]
すみませんが、issueは使い方をきくところではありません。
Rubyの知識がある方ならわかるかとおもいます。

**Comment by yuuna** [comment]
readmeにもかいています。
ドキュメントをお読みいただくか、著しくはソースコードをお読みください。

**Comment by hardreggaecafe** [comment]
大変失礼いたしました。Readmeは読んだのですが、画面からAccessToken取得する箇所についてはわかったので実装しましたが、Tokenの更新については出ていないように見えたので、再度確認します。
ありがとうございました。
